//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzas.Application.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorsMessages_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessages_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pizzas.Application.Resources.Errors.ErrorsMessages.en", typeof(ErrorsMessages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Item Not Found.
        /// </summary>
        internal static string BasketItemNotFound {
            get {
                return ResourceManager.GetString("BasketItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Not Found.
        /// </summary>
        internal static string BasketNotFound {
            get {
                return ResourceManager.GetString("BasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City format is invalid.
        /// </summary>
        internal static string CityInvalid {
            get {
                return ResourceManager.GetString("CityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must not exceed {0} characters.
        /// </summary>
        internal static string CityMaxLength {
            get {
                return ResourceManager.GetString("CityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country format is invalid.
        /// </summary>
        internal static string CountryInvalid {
            get {
                return ResourceManager.GetString("CountryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country must not exceed {0} characters.
        /// </summary>
        internal static string CountryMaxLength {
            get {
                return ResourceManager.GetString("CountryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Info Not Found.
        /// </summary>
        internal static string DeliveryInfoNotFound {
            get {
                return ResourceManager.GetString("DeliveryInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and password cannot beempty.
        /// </summary>
        internal static string EmailAndPasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailAndPasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient not found.
        /// </summary>
        internal static string IngredientNotFound {
            get {
                return ResourceManager.GetString("IngredientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is invalid or has expired.
        /// </summary>
        internal static string InvalidOrExpiredOtp {
            get {
                return ResourceManager.GetString("InvalidOrExpiredOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and include letters and numbers.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Basket Items Found.
        /// </summary>
        internal static string NoBasketItemsFound {
            get {
                return ResourceManager.GetString("NoBasketItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delivery Infos Found.
        /// </summary>
        internal static string NoDeliveryInfosFound {
            get {
                return ResourceManager.GetString("NoDeliveryInfosFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ingredients found.
        /// </summary>
        internal static string NoIngredientsFound {
            get {
                return ResourceManager.GetString("NoIngredientsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No order items found.
        /// </summary>
        internal static string NoOrderItemsFound {
            get {
                return ResourceManager.GetString("NoOrderItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders found.
        /// </summary>
        internal static string NoOrdersFound {
            get {
                return ResourceManager.GetString("NoOrdersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions found.
        /// </summary>
        internal static string NoPermissionsFound {
            get {
                return ResourceManager.GetString("NoPermissionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pizza ingredients found.
        /// </summary>
        internal static string NoPizzaIngredientsFound {
            get {
                return ResourceManager.GetString("NoPizzaIngredientsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pizzas found.
        /// </summary>
        internal static string NoPizzasFound {
            get {
                return ResourceManager.GetString("NoPizzasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews found.
        /// </summary>
        internal static string NoReviewsFound {
            get {
                return ResourceManager.GetString("NoReviewsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles found.
        /// </summary>
        internal static string NoRolesFound {
            get {
                return ResourceManager.GetString("NoRolesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item not found.
        /// </summary>
        internal static string OrderItemNotFound {
            get {
                return ResourceManager.GetString("OrderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not found.
        /// </summary>
        internal static string PermissionNotFound {
            get {
                return ResourceManager.GetString("PermissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza ingredient not found.
        /// </summary>
        internal static string PizzaIngredientNotFound {
            get {
                return ResourceManager.GetString("PizzaIngredientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza not found.
        /// </summary>
        internal static string PizzaNotFound {
            get {
                return ResourceManager.GetString("PizzaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait before requestinga new OTP.
        /// </summary>
        internal static string PleaseWaitBeforeRequesting {
            get {
                return ResourceManager.GetString("PleaseWaitBeforeRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code format is invalid.
        /// </summary>
        internal static string PostalCodeInvalid {
            get {
                return ResourceManager.GetString("PostalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code must not exceed {0} characters.
        /// </summary>
        internal static string PostalCodeMaxLength {
            get {
                return ResourceManager.GetString("PostalCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code is required.
        /// </summary>
        internal static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not found.
        /// </summary>
        internal static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State format is invalid.
        /// </summary>
        internal static string StateInvalid {
            get {
                return ResourceManager.GetString("StateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must not exceed {0} characters.
        /// </summary>
        internal static string StateMaxLength {
            get {
                return ResourceManager.GetString("StateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        internal static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street format is invalid.
        /// </summary>
        internal static string StreetInvalid {
            get {
                return ResourceManager.GetString("StreetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street must not exceed {0} characters.
        /// </summary>
        internal static string StreetMaxLength {
            get {
                return ResourceManager.GetString("StreetMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required.
        /// </summary>
        internal static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to continue.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such account found. Lookslike it’s time to sign up 😉.
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain only lowercase letters.
        /// </summary>
        internal static string UsernameMustBeLowercase {
            get {
                return ResourceManager.GetString("UsernameMustBeLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
