//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzas.Application.Resources.Errors {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorsMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pizzas.Application.Resources.Errors.ErrorsMessages", typeof(ErrorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BasketItemNotFound {
            get {
                return ResourceManager.GetString("BasketItemNotFound", resourceCulture);
            }
        }
        
        internal static string NoBasketItemsFound {
            get {
                return ResourceManager.GetString("NoBasketItemsFound", resourceCulture);
            }
        }
        
        internal static string BasketNotFound {
            get {
                return ResourceManager.GetString("BasketNotFound", resourceCulture);
            }
        }
        
        internal static string DeliveryInfoNotFound {
            get {
                return ResourceManager.GetString("DeliveryInfoNotFound", resourceCulture);
            }
        }
        
        internal static string NoDeliveryInfosFound {
            get {
                return ResourceManager.GetString("NoDeliveryInfosFound", resourceCulture);
            }
        }
        
        internal static string NoIngredientsFound {
            get {
                return ResourceManager.GetString("NoIngredientsFound", resourceCulture);
            }
        }
        
        internal static string IngredientNotFound {
            get {
                return ResourceManager.GetString("IngredientNotFound", resourceCulture);
            }
        }
        
        internal static string OrderItemNotFound {
            get {
                return ResourceManager.GetString("OrderItemNotFound", resourceCulture);
            }
        }
        
        internal static string NoOrderItemsFound {
            get {
                return ResourceManager.GetString("NoOrderItemsFound", resourceCulture);
            }
        }
        
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        internal static string NoOrdersFound {
            get {
                return ResourceManager.GetString("NoOrdersFound", resourceCulture);
            }
        }
        
        internal static string NoPermissionsFound {
            get {
                return ResourceManager.GetString("NoPermissionsFound", resourceCulture);
            }
        }
        
        internal static string PermissionNotFound {
            get {
                return ResourceManager.GetString("PermissionNotFound", resourceCulture);
            }
        }
        
        internal static string PizzaIngredientNotFound {
            get {
                return ResourceManager.GetString("PizzaIngredientNotFound", resourceCulture);
            }
        }
        
        internal static string NoPizzaIngredientsFound {
            get {
                return ResourceManager.GetString("NoPizzaIngredientsFound", resourceCulture);
            }
        }
        
        internal static string NoPizzasFound {
            get {
                return ResourceManager.GetString("NoPizzasFound", resourceCulture);
            }
        }
        
        internal static string PizzaNotFound {
            get {
                return ResourceManager.GetString("PizzaNotFound", resourceCulture);
            }
        }
        
        internal static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        internal static string NoReviewsFound {
            get {
                return ResourceManager.GetString("NoReviewsFound", resourceCulture);
            }
        }
        
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        internal static string NoRolesFound {
            get {
                return ResourceManager.GetString("NoRolesFound", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        internal static string EmailAndPasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailAndPasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        internal static string NotEnoughIngredientAvailable {
            get {
                return ResourceManager.GetString("NotEnoughIngredientAvailable", resourceCulture);
            }
        }
        
        internal static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        internal static string InvalidOrExpiredOtp {
            get {
                return ResourceManager.GetString("InvalidOrExpiredOtp", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        internal static string UsernameMustBeLowercase {
            get {
                return ResourceManager.GetString("UsernameMustBeLowercase", resourceCulture);
            }
        }
        
        internal static string PleaseWaitBeforeRequesting {
            get {
                return ResourceManager.GetString("PleaseWaitBeforeRequesting", resourceCulture);
            }
        }
        
        internal static string CannotChangeStatusOfFinalizedOrder {
            get {
                return ResourceManager.GetString("CannotChangeStatusOfFinalizedOrder", resourceCulture);
            }
        }
    }
}
